### ISSUE TITLE
Please rebuild this in Swift

### ISSUE THREAD

**Issue by atentis** [googleads/googleads-ima-tvos-dai#1]
I am not sure why this was written in Objective-C since Apple switched to Swift many years ago. 

Please write this in Swift as its much harder to implement in its current form to a typical tvOS app.

**Comment by Kiro705** [comment]
Based on the [Swift advanced sample](https://github.com/googleads/googleads-ima-tvos-dai/tree/main/Swift/AdvancedExample), I think this issue can be closed. Please reopen if this sample does not fulfill the requirements.
